.TH PHRASEBOOKS 1 "APRIL 14, 2016"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
phrasebooks \- a tool to manage phrasebooks and load the selected word or phrase into an external dictionary.
.SH SYNOPSIS
.B phrasebooks
.br
.SH DESCRIPTION
The purpose of this applications is to manage English phrasebooks and load
the specified English word or text into an external dictionary. The application
DOES NOT translate a text, it only loads it into an external dictionary to get
the full translation with synonyms, examples, articles etc.

The application is intended to a person who'd like to learn an English vocabulary
(other languages are not supported at this time), but his/her favorite dictionary
doesn't support advanced phrasebooks.

If your favorite dictionary supports advanced phrasebooks,
then you don't need this application.
.SH AUTHOR
phrasebooks was written by Dmitry Baryshev.
.PP
This manual page was written by Dmitry Baryshev <dima8w@gmail.com>,
for the Debian project (but may be used by others).
